### ISSUE TITLE
CLA Bot should check also on deactivated partners

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#170] opened 2022-02-18 21:15 UTC
If not, ex-exployees with their proper CLA are shown as missing when doing migrations.

**Comment by sbidoul** [comment] 2022-04-03 10:25
Duplicate of https://github.com/OCA/maintainer-tools/issues/527 and wrong project.

**Closed by sbidoul** 2022-04-03 10:25 UTC
Labels: bug

**Comment by gurneyalex** [comment] 2022-04-06 11:49
well actually not the wrong project @sbidoul : https://github.com/OCA/oca-github-bot/tree/clabot ;)

**Comment by sbidoul** [comment] 2022-04-06 12:23
@gurneyalex yes, sure I remember that PR. But do we want to finish that one, or rather keep the existing bot on life support and invest time in setting up a paperless CLA process ?

**Comment by gurneyalex** [comment] 2022-04-06 12:25
this is actually the branch where the source code of the legacty runbot is living. There was another PR to migrate it to the gitbot, but we decided against it in the end. 

I'm all in favor of setting up a paperless CLA process ;)

**Comment by gurneyalex** [comment] 2022-04-06 12:26
(and killing the legacy runbot)

**Comment by sbidoul** [comment] 2022-04-06 12:28
> this is actually the branch where the source code of the legacty runbot is living

Oh, ah, TIL. Good to know. I was mixing with https://github.com/OCA/maintainer-tools/blob/master/tools/github_clabot_hook.py.

**Comment by pedrobaeza** [comment] 2022-04-06 12:29
And meanwhile can we include deactivated partners? It shouldn't be too hard.

**Comment by pedrobaeza** [comment] 2022-04-06 12:49
Thanks!
